# This is a generated file. Not intended for manual editing.
services:
  basket.api:
    build:
      context: "J:\\Users\\davis\\RiderProjects\\CSharpLearningMicroservices"
      dockerfile: "src/Services/Basket/Basket.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net10.0/Basket.API.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "basket.api:dev"
    ports: []
    volumes:
    - "J:\\Users\\davis\\RiderProjects\\CSharpLearningMicroservices\\src\\Services\\\
      Basket\\Basket.API:/app:rw"
    - "J:\\Users\\davis\\RiderProjects\\CSharpLearningMicroservices:/src:rw"
    - "C:\\Users\\davis\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
  catalog.api:
    build:
      context: "J:\\Users\\davis\\RiderProjects\\CSharpLearningMicroservices"
      dockerfile: "src/Services/Catalog/Catalog.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net10.0/Catalog.Api.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "catalog.api:dev"
    ports: []
    volumes:
    - "J:\\Users\\davis\\RiderProjects\\CSharpLearningMicroservices\\src\\Services\\\
      Catalog\\Catalog.Api:/app:rw"
    - "J:\\Users\\davis\\RiderProjects\\CSharpLearningMicroservices:/src:rw"
    - "C:\\Users\\davis\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
