services:
  catalogdb:
    image: postgres
  
  basketdb:
    image: postgres
  
  distributedcache:
    image: redis
  
  orderdb:
    image: mcr.microsoft.com/mssql/server
  
  messagebroker:
    image: rabbitmq:management
  
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalog.api
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.Api/Dockerfile

  basket.api:
    image: basket.api
    build:
      context: .
      dockerfile: src/Services/Basket/Basket.API/Dockerfile
  
  discount.grpc:
    image: discount.grpc
    build:
      context: .
      dockerfile: src/Services/Discount.Grpc/Dockerfile
  
  ordering.api:
    image: ordering.api
    build:
      context: .
      dockerfile: src/Services/Ordering.API/Dockerfile

  yarpapigateway:
    image: yarpapigateway
    build:
      context: .
      dockerfile: src/YarpApiGateway/Dockerfile
  
  shopping.web:
    image: shopping.web
    build:
      context: .
      dockerfile: src/WebApps/Shopping.Web/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:
  discount_data:
  ordering_data:
